version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    links:
     - db
    volumes:
     - .:/usr/app
    container_name: node
    command: npm start

  db:
    image: postgres:11.2-alpine
    restart: always
    ports:
      - "35432:5432"
    container_name: postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: music-stream-app
