version: '3'

services:
  app:
    image: node:12.10.0-alpine
    container_name: music-app-server
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - database
    command: sh -c "cd /usr/app/ && npm i && npm run dev"

  database:
    image: mongo
    container_name: music-app-database
    ports:
      - '27017:27017'
    volumes:
      - /usr/mongodb/data
    logging:
      driver: 'none'
